version: '3.8'

services:
  nacos-standalone-auth:
    image: nacos/nacos-server:latest
    container_name: nacos-standalone
    environment:
      - MODE=standalone
    ports:
      - "8848:8848"
      - "9848:9848"
    restart: unless-stopped
