version: '3.8'

services:
  mongo:
    image: mongo:7.0.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - ./datadir:/data/db
    ports:
      - "27017:27017"
