version: '2'
services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
        - 27017:27017
    volumes:
        - ./datadir:/data/db
    command: mongod --auth
    tty: true
